# TODO: This workflow duplicates cloudflare-preview.yml functionality
# Consider consolidating into a single workflow
name: PR Cloudflare Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - id: deploy
        if: github.event.action != 'closed'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          packageManager: pnpm
          command: |
            deploy --name cf-mcp-pr-${{ github.event.pull_request.number }} \
              --var BASE_URL=https://cf-mcp-pr-${{ github.event.pull_request.number }}.asi-cloud.workers.dev
      - name: Comment Preview URL
        if: github.event.action != 'closed'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: "Cloudflare preview available at https://cf-mcp-pr-${{ github.event.pull_request.number }}.asi-cloud.workers.dev"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Preview Deployment
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          packageManager: pnpm
          command: delete cf-mcp-pr-${{ github.event.pull_request.number }}
      - name: Remove Preview Comment
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          delete: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
